---
apiVersion: v1
kind: Namespace
metadata:
  name: gameapp-namespace
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gameapp-pvc
  namespace: gameapp-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gameapp1-deployment
  namespace: gameapp-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gameapp1
  template:
    metadata:
      labels:
        app: gameapp1
    spec:
      containers:
        - name: gameapp1
          image: davidokpe/nvit-gameapp1:lts
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: app-data
              mountPath: /home/ubuntu/data/
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: gameapp-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gameapp2-deployment
  namespace: gameapp-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gameapp2
  template:
    metadata:
      labels:
        app: gameapp2
    spec:
      containers:
        - name: gameapp2
          image: davidokpe/nvit-gameapp2:lts
          ports:
            - containerPort: 5001
          volumeMounts:
            - name: app-data
              mountPath: /home/ubuntu/data/
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: gameapp-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: gameapp1-service
  namespace: gameapp-namespace
spec:
  type: NodePort
  selector:
    app: gameapp1
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: gameapp2-service
  namespace: gameapp-namespace
spec:
  type: NodePort
  selector:
    app: gameapp2
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30002
